# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c16e27251a8a8f23e1c74c7f879610d51d7e6098a8ebe79040e17dea9ee3752d75ce50b5aafd6e958d5a0059e111bada3f6ddfad80581b843e76ff0a46e52be

test:
  secret_key_base: 4bb2b12c8401db0946318f019d7f47e79fa50de4f1edd958bec22f6b6529bbdc4f2d72c6b7d4c416365691d59689b15b7d1ded65fad27b19e9dbb5fb8b1b71b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
